version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    command:
      - etcd
      - --data-dir
      - /etcd
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -advertise-client-urls=http://127.0.0.1:2379
    volumes:
      - ./data/etcd:/etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      retries: 4
      timeout: 32s
      interval: 32s

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    command:
      - minio
      - server
      - /minio_data
      - --console-address
      - :9001
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - ./data/minio:/minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 4
      timeout: 16s
      interval: 32s

  vector_db:
    image: milvusdb/milvus:v2.3.3
    ports:
      - 9091:9091
      - 19530:19530
    depends_on:
      - etcd
      - minio
    command:
      - milvus
      - run
      - standalone
    security_opt:
      - seccomp:unconfined
    environment:
      MINIO_ADDRESS: minio:9000
      ETCD_ENDPOINTS: etcd:2379
    volumes:
      - ./data/milvusdb:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      retries: 4
      timeout: 32s
      interval: 32s
      start_period: 128s
